export const workingFixture = {
  fixture: {
    "fixtures-results": {
      team: {
        name: "Manchester United",
        id: 13,
      },
      matches: [
        {
          date: "2023-08-14",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 457919,
          time: "20:00",
          "home-team": {
            score: 1,
            "half-time-score": 0,
            name: "Manchester United",
            id: 13,
          },
          referee: "Simon Hooper",
          "away-team": {
            score: 0,
            "half-time-score": 0,
            name: "Wolverhampton Wanderers",
            id: 44,
          },
          attendance: 73358,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-08-19",
          venue: "Tottenham Hotspur Stadium",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 457927,
          time: "17:30",
          "home-team": {
            score: 2,
            "half-time-score": 0,
            name: "Tottenham Hotspur",
            id: 19,
          },
          referee: "Michael Oliver",
          "away-team": {
            score: 0,
            "half-time-score": 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 61910,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-08-26",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 457937,
          time: "15:00",
          "home-team": {
            score: 3,
            "half-time-score": 1,
            name: "Manchester United",
            id: 13,
          },
          referee: "Stuart Attwell",
          "away-team": {
            score: 2,
            "half-time-score": 2,
            name: "Nottingham Forest",
            id: 32,
          },
          attendance: 73595,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-09-03",
          venue: "Emirates Stadium",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 467986,
          time: "16:30",
          "home-team": {
            score: 3,
            "half-time-score": 1,
            name: "Arsenal",
            id: 1,
          },
          referee: "Anthony Taylor",
          "away-team": {
            score: 1,
            "half-time-score": 1,
            name: "Manchester United",
            id: 13,
          },
          attendance: 60192,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-09-16",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 457954,
          time: "15:00",
          "home-team": {
            score: 1,
            "half-time-score": 0,
            name: "Manchester United",
            id: 13,
          },
          referee: "Jarred Gillett",
          "away-team": {
            score: 3,
            "half-time-score": 1,
            name: "Brighton & Hove Albion",
            id: 21,
          },
          attendance: 73592,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-09-20",
          venue: "Allianz Arena",
          round: {
            name: "Group A",
            id: 13,
          },
          competition: {
            name: "UEFA Champions League",
            id: 24,
          },
          id: 478456,
          time: "20:00",
          "home-team": {
            score: 4,
            "half-time-score": 2,
            name: "Bayern Munich",
            id: 484,
          },
          referee: "Glenn Nyberg",
          "away-team": {
            score: 3,
            "half-time-score": 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 75000,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-09-23",
          venue: "Turf Moor",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 457963,
          time: "20:00",
          "home-team": {
            score: 0,
            "half-time-score": 0,
            name: "Burnley",
            id: 22,
          },
          referee: "Tony Harrington",
          "away-team": {
            score: 1,
            "half-time-score": 1,
            name: "Manchester United",
            id: 13,
          },
          attendance: 21720,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-09-26",
          venue: "Old Trafford",
          round: {
            name: "Third Round",
            id: 29,
          },
          competition: {
            name: "Carabao Cup",
            id: 22,
          },
          id: 478422,
          time: "20:00",
          "home-team": {
            score: 3,
            "half-time-score": 2,
            name: "Manchester United",
            id: 13,
          },
          referee: "Salisbury Michael",
          "away-team": {
            score: 0,
            "half-time-score": 0,
            name: "Crystal Palace",
            id: 8,
          },
          attendance: 72842,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-09-30",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 457974,
          time: "15:00",
          "home-team": {
            score: 0,
            "half-time-score": 0,
            name: "Manchester United",
            id: 13,
          },
          referee: "Chris Kavanagh",
          "away-team": {
            score: 1,
            "half-time-score": 1,
            name: "Crystal Palace",
            id: 8,
          },
          attendance: 73428,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-10-03",
          venue: "Old Trafford",
          round: {
            name: "Group A",
            id: 13,
          },
          competition: {
            name: "UEFA Champions League",
            id: 24,
          },
          id: 478510,
          time: "20:00",
          "home-team": {
            score: 2,
            "half-time-score": 1,
            name: "Manchester United",
            id: 13,
          },
          referee: "Ivan Kružliak",
          "away-team": {
            score: 3,
            "half-time-score": 1,
            name: "Galatasaray",
            id: 632,
          },
          attendance: 73204,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-10-07",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 457987,
          time: "15:00",
          "home-team": {
            score: 2,
            "half-time-score": 0,
            name: "Manchester United",
            id: 13,
          },
          referee: "Andy Madley",
          "away-team": {
            score: 1,
            "half-time-score": 1,
            name: "Brentford",
            id: 49,
          },
          attendance: 73453,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-10-21",
          venue: "Bramall Lane",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 478779,
          time: "20:00",
          "home-team": {
            score: 1,
            "half-time-score": 1,
            name: "Sheffield United",
            id: 38,
          },
          referee: "Michael Oliver",
          "away-team": {
            score: 2,
            "half-time-score": 1,
            name: "Manchester United",
            id: 13,
          },
          attendance: 31543,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-10-24",
          venue: "Old Trafford",
          round: {
            name: "Group A",
            id: 13,
          },
          competition: {
            name: "UEFA Champions League",
            id: 24,
          },
          id: 478526,
          time: "20:00",
          "home-team": {
            score: 1,
            "half-time-score": 0,
            name: "Manchester United",
            id: 13,
          },
          referee: "Marco Guida",
          "away-team": {
            score: 0,
            "half-time-score": 0,
            name: "FC Copenhagen",
            id: 570,
          },
          attendance: 73249,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-10-29",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 478003,
          time: "15:30",
          "home-team": {
            score: 0,
            "half-time-score": 0,
            name: "Manchester United",
            id: 13,
          },
          referee: "Paul Tierney",
          "away-team": {
            score: 3,
            "half-time-score": 1,
            name: "Manchester City",
            id: 12,
          },
          attendance: 73502,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-11-01",
          venue: "Old Trafford",
          round: {
            name: "Fourth Round",
            id: 31,
          },
          competition: {
            name: "Carabao Cup",
            id: 22,
          },
          id: 480101,
          time: "20:15",
          "home-team": {
            score: 0,
            "half-time-score": 0,
            name: "Manchester United",
            id: 13,
          },
          referee: "Robert Jones",
          "away-team": {
            score: 3,
            "half-time-score": 2,
            name: "Newcastle United",
            id: 15,
          },
          attendance: 72484,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-11-04",
          venue: "Craven Cottage",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458013,
          time: "12:30",
          "home-team": {
            score: 0,
            "half-time-score": 0,
            name: "Fulham",
            id: 10,
          },
          referee: "John Brooks",
          "away-team": {
            score: 1,
            "half-time-score": 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 24415,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-11-08",
          venue: "Parken",
          round: {
            name: "Group A",
            id: 13,
          },
          competition: {
            name: "UEFA Champions League",
            id: 24,
          },
          id: 478542,
          time: "20:00",
          "home-team": {
            score: 4,
            "half-time-score": 2,
            name: "FC Copenhagen",
            id: 570,
          },
          referee: "Donatas Rumsas",
          "away-team": {
            score: 3,
            "half-time-score": 2,
            name: "Manchester United",
            id: 13,
          },
          attendance: 36099,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-11-11",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458027,
          time: "15:00",
          "home-team": {
            score: 1,
            "half-time-score": 0,
            name: "Manchester United",
            id: 13,
          },
          referee: "Graham Scott",
          "away-team": {
            score: 0,
            "half-time-score": 0,
            name: "Luton Town",
            id: 57,
          },
          attendance: 73599,
          status: {
            short: "FT",
            full: "Full Time",
          },
        },
        {
          date: "2023-11-26",
          venue: "Goodison Park",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 480482,
          time: "16:30",
          "home-team": {
            score: 0,
            name: "Everton",
            id: 9,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "4.30pm",
            full: "Kick off 4.30pm",
          },
        },
        {
          date: "2023-11-29",
          venue: "Rams Global Stadium",
          round: {
            name: "Group A",
            id: 13,
          },
          competition: {
            name: "UEFA Champions League",
            id: 24,
          },
          id: 478549,
          time: "17:45",
          "home-team": {
            score: 0,
            name: "Galatasaray",
            id: 632,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "5.45pm",
            full: "Kick off 5.45pm",
          },
        },
        {
          date: "2023-12-02",
          venue: "St. James' Park",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458047,
          time: "20:00",
          "home-team": {
            score: 0,
            name: "Newcastle United",
            id: 15,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "8pm",
            full: "Kick off 8pm",
          },
        },
        {
          date: "2023-12-06",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458059,
          time: "20:15",
          "home-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          "away-team": {
            score: 0,
            name: "Chelsea",
            id: 7,
          },
          attendance: 0,
          status: {
            short: "8.15pm",
            full: "Kick off 8.15pm",
          },
        },
        {
          date: "2023-12-09",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458066,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          "away-team": {
            score: 0,
            name: "AFC Bournemouth",
            id: 47,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2023-12-12",
          venue: "Old Trafford",
          round: {
            name: "Group A",
            id: 13,
          },
          competition: {
            name: "UEFA Champions League",
            id: 24,
          },
          id: 478566,
          time: "20:00",
          "home-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          "away-team": {
            score: 0,
            name: "Bayern Munich",
            id: 484,
          },
          attendance: 0,
          status: {
            short: "8pm",
            full: "Kick off 8pm",
          },
        },
        {
          date: "2023-12-17",
          venue: "Anfield",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 480799,
          time: "16:30",
          "home-team": {
            score: 0,
            name: "Liverpool",
            id: 11,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "4.30pm",
            full: "Kick off 4.30pm",
          },
        },
        {
          date: "2023-12-23",
          venue: "London Stadium",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458088,
          time: "12:30",
          "home-team": {
            score: 0,
            name: "West Ham United",
            id: 42,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "12.30pm",
            full: "Kick off 12.30pm",
          },
        },
        {
          date: "2023-12-26",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458097,
          time: "20:00",
          "home-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          "away-team": {
            score: 0,
            name: "Aston Villa",
            id: 2,
          },
          attendance: 0,
          status: {
            short: "8pm",
            full: "Kick off 8pm",
          },
        },
        {
          date: "2023-12-30",
          venue: "The City Ground",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458106,
          time: "17:30",
          "home-team": {
            score: 0,
            name: "Nottingham Forest",
            id: 32,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "5.30pm",
            full: "Kick off 5.30pm",
          },
        },
        {
          date: "2024-01-14",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 480815,
          time: "16:30",
          "home-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          "away-team": {
            score: 0,
            name: "Tottenham Hotspur",
            id: 19,
          },
          attendance: 0,
          status: {
            short: "4.30pm",
            full: "Kick off 4.30pm",
          },
        },
        {
          date: "2024-01-30",
          venue: "Molineux Stadium",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458126,
          time: "19:45",
          "home-team": {
            score: 0,
            name: "Wolverhampton Wanderers",
            id: 44,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "7.45pm",
            full: "Kick off 7.45pm",
          },
        },
        {
          date: "2024-02-03",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458137,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          "away-team": {
            score: 0,
            name: "West Ham United",
            id: 42,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2024-02-10",
          venue: "Villa Park",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458140,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "Aston Villa",
            id: 2,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2024-02-17",
          venue: "Kenilworth Road",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458154,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "Luton Town",
            id: 57,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2024-02-24",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458167,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          "away-team": {
            score: 0,
            name: "Fulham",
            id: 10,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2024-03-02",
          venue: "Etihad Stadium",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458175,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "Manchester City",
            id: 12,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2024-03-09",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458187,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          "away-team": {
            score: 0,
            name: "Everton",
            id: 9,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2024-03-16",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458197,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          "away-team": {
            score: 0,
            name: "Sheffield United",
            id: 38,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2024-03-30",
          venue: "Gtech Community Stadium",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458202,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "Brentford",
            id: 49,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2024-04-03",
          venue: "Stamford Bridge",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458216,
          time: "19:45",
          "home-team": {
            score: 0,
            name: "Chelsea",
            id: 7,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "7.45pm",
            full: "Kick off 7.45pm",
          },
        },
        {
          date: "2024-04-06",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458226,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          "away-team": {
            score: 0,
            name: "Liverpool",
            id: 11,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2024-04-13",
          venue: "Vitality Stadium",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458230,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "AFC Bournemouth",
            id: 47,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2024-04-20",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458246,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          "away-team": {
            score: 0,
            name: "Newcastle United",
            id: 15,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2024-04-27",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458254,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          "away-team": {
            score: 0,
            name: "Burnley",
            id: 22,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2024-05-04",
          venue: "Selhurst Park",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458265,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "Crystal Palace",
            id: 8,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2024-05-11",
          venue: "Old Trafford",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458274,
          time: "15:00",
          "home-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          "away-team": {
            score: 0,
            name: "Arsenal",
            id: 1,
          },
          attendance: 0,
          status: {
            short: "3pm",
            full: "Kick off 3pm",
          },
        },
        {
          date: "2024-05-19",
          venue: "The American Express Community Stadium",
          competition: {
            name: "Premier League",
            id: 1,
          },
          id: 458282,
          time: "16:00",
          "home-team": {
            score: 0,
            name: "Brighton & Hove Albion",
            id: 21,
          },
          "away-team": {
            score: 0,
            name: "Manchester United",
            id: 13,
          },
          attendance: 0,
          status: {
            short: "4pm",
            full: "Kick off 4pm",
          },
        },
      ],
    },
  },
};
